# web driver
#url: 'https://aicloud.sbercloud.ru'
url: 'http://test.aicloud.sbercloud.ru/'
implicit_timeout: 5
window_size: 'maximize'

# grid / selenoid
protocol: 'http'
host:     'localhost'
port:     '4444'
path:     '/wd/hub'

# any data
username: 'aslagunkov@sbercloud.ru'
password: 'Aslagunkov@sbercloud1'

# caps
capabilities:
    browserName: 'chrome'
    unexpectedAlertBehaviour: 'accept'
    enableVNC: True
    screenResolution: '1920x1080x24'
    loggingPrefs:
        browser: 'INFO'
    chromeOptions:
        args: ['--disable-infobars']
