# web driver
url: 'https://aicloud.sbercloud.ru'
implicit_timeout: 5
window_size: 'maximize'

# grid / selenoid
protocol: 'http'
host:     'localhost'
port:     '4444'
path:     '/wd/hub'

# aicloud
ac_url: https://aicloud.sbercloud.ru
username: aslagunkov@sbercloud.ru
password: Aslagunkov@sbercloud1